backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages"
    files: 
      - file: 'content/_index.en.md'
        label: "Home Page"
        name: "home"
          - {label: Title, name: title, widget: string}
          - {label: Weight, name: weight, widget: number}
          - {label: Body, name: body, widget: markdown}


